type Config = {
    gapsOuterTop: number,
    gapsOuterBottom: number,
    gapsOuterLeft: number,
    gapsOuterRight: number,
    gapsInnerHorizontal: number,
    gapsInnerVertical: number,
    manualScrollStep: number,
    manualResizeStep: number,
    offScreenOpacity: number,
    untileOnDrag: boolean,
    stackColumnsByDefault: boolean,
    resizeNeighborColumn: boolean,
    reMaximize: boolean,
    skipSwitcher: boolean,
    scrollingLazy: boolean,
    scrollingCentered: boolean,
    scrollingGrouped: boolean,
    tiledKeepBelow: boolean,
    floatingKeepAbove: boolean,
    windowRules: string,
};
